:REVEAL_PROPERTIES:
#+REVEAL_REVEAL_JS_VERSION: 4
#+REVEAL_TRANS: None
#+REVEAL_THEME: serif
#+OPTIONS: timestamp:nil toc:1 num:nil
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_PLUGINS: notes
#+REVEAL_EXTRA_CSS: modifications.css
#+REVEAL_SLIDE_FOOTER: Lick the Toad: MIAM Colloquium Jan, 2023.
:END:


#+Title: Lick the Toad
#+SUBTITLE: A web based interface for displaced agencies in musical interaction.
#+Author: Konstantinos Vasilakos

* Introduction
** Back to the parlour
#+BEGIN_QUOTE
Imagine a weekend afternoon in a middle class parlour during the second half of the nineteenth century: a soiree, with music performed live by family members gathered around the piano. This scene - once a common occurrence that fostered creative social interaction - became increasingly rare; being displaced by substitute social behaviours arising from technological developments such as sound recording (van der Merwe, 1989), television, etc. Furthermore, as the schism between ‘popular’ and ‘art’ deepened, and the latter demanded increasing levels of virtuosity in order to realise musical ideas, performance of certain strands of contemporary music became nearly impossible for anyone but professionals; disappearing from the ‘soiree’ repertoire.(Fischman, 2011)
#+END_QUOTE
** Bridging the audience agency in musical interaction
Ltt is a web interface designed for bridging the gap between performer(s) and audience, allowing former and latter to engage interactively.
* Implementation notes
#+ATTR_REVEAL: :frag (appear)
1) Real time communication using web sockets[fn:1]
2) Sonifications on users' devices using Markov Chain instructed by a Neural Network (regression algorithm).
3) OSC communication with: MaxMSP, SuperCollider, Pure Data, etc.

* Networked systems
** Looking Back
#+ATTR_HTML: :width 35% :align center
https://upload.wikimedia.org/wikipedia/commons/0/00/Telharmonium_-_Scientific_American_1907_%28zoomed_400%25%2C_brightened%29.jpg

[[https://commons.wikimedia.org/w/index.php?curid=112285881/][Unknown author - The World's Work, June 1906, vol. XII, no. II, Public Domain]]

#+BEGIN_NOTES
To understand networked music system first a paraller maybe drawn with other examples of primitive distributed systems in music making. In 1895 Thaddeus Cahill submitted his first patent for the Telharmonium, influenced by other similar creations of the time in Europe and beyond. What was common ground for these all was the idea of using modern available tellecommunications, to distribute live music electrically and most important, remotely, displaced from the actual site of the music performance. Therefore, modern technology apparatus and implicit networking was always in the forefront of pioneering music.
#+END_NOTES

** Influences
“The Art of and Apparatus for Generating and Distributing Music Electrically”.[fn:3] (Crab, 2013)
#+NAME: Table_Crab_Telharmonium
| Cahill    | Telharmonium      | 1895/97 |
|-----------+-------------------+---------|
| Puskás    | Telefonhírmondó   |    1893 |
| Gray      | Musical Telegraph |    1874 |
| Ader      | Théâtrophone      |    1881 |
| Soemering | n/a               |    1809 |



** Looking Forward
Slightly more recent takes, on this, Networked Music Systems (Collins, N., & Escrivan Rincón, J. d. 2011).

Some works by the author in this field:
- [[https://serkansevilgen.com/docs/01_ICLC_2021_Sevilgen_Vasilakos_Wilson.pdf][BEER Pea Stew: Recalibrated]] (Wilson, Vasilakos, Lorway, Margetson, Yeung).
- [[https://serkansevilgen.com/docs/01_ICLC_2021_Sevilgen_Vasilakos_Wilson.pdf][ICE: Symphony in Blue 2.0]] Based on Kamran Ince's initial work (Vasilakos, Sevilgen, Dagdeviren, Wilson)

* Ltt: ML in the browser
#+ATTR_HTML: :width 25% :align center
https://media.giphy.com/media/o7NKhab3HqG4tgVHpr/giphy.gif

#+BEGIN_NOTES
A client allows to train a model in a web browser and trigger predictions based on a regression algorithm. Once the training process is done the system offers a visualization of the output values. The pitch of the patterns is based on a Markov chain module which is  generating predictions based on the neural network regression output values. At the same time, the client is able to send this data to another clients "listening" for incoming OSC messages (e.g., SuperCollider).
#+END_NOTES
* Ltt's creative directions
:PROPERTIES:
:reveal_background: img/sonified_image.jpg
:reveal_background_size: 75%
:reveal_background_trans: slide
:reveal_background_opacity: 0.99
:END:

#+BEGIN_NOTES
Ltt has been used as a standalone app for collective sonifications of bystanders and remote participants but since then it has taken many spins including a real time chat engine amongst peers.
#+END_NOTES

** Live Coding: what now?
In live coding performances, there is always the question of how a coder is taking their decisions while changing the code on the fly, described also as "kairotic coding". (Cocker, E. 2018).

*** Ongoing Work
A study on live coding using ltt and stochastic processes[fn:2] in SuperCollider's JITLib.
#+ATTR_REVEAL: :code_attribs
#+BEGIN_SRC sclang
{
	[nil].choose;
}
#+END_SRC

[[youtube:IrGk0yrfbOY][[nil].choose.play;​]]

* Discussion
While ltt serves both as a standalone and live coding tool, it arguably allows for a greater coherence amongst peers on live performance. Similar to the concept of "back to the parlour" (Fischman, 2011) where members of the audience are able to enact an impromptu improvisation.
* Thanks
Courtesy to the majestic Org mode
#+Attr_html: :width 15% :align center
https://upload.wikimedia.org/wikipedia/commons/a/a6/Org-mode-unicorn.svg

...and the powerful SuperCollider
#+ATTR_HTML: :width 15% :align center
https://upload.wikimedia.org/wikipedia/commons/6/60/SuperCollider_logo.svg

* Footnotes
[fn:3] A [[https://120years.net/wordpress/the-telharmonium-thaddeus-cahill-usa-1897/][new field of electronic musical instruments]] and [[https://artsandculture.google.com/story/iAWRKDY1jD1jKA][electronic musical instruments creation using telegraphy]].
[fn:2] Stochastic synthesis is coined by Iannis Xenakis, with some of the most famous works [[https://www.youtube.com/watch?v=TNWFITZrvxo&ab_channel=TheHouseofHiddenKnowledge][La Légende d'Eer (1977/78)]] and Gendy system.
[fn:1] Web sockets is a real time communication mechanism that allow web pages to send and receive data amongst peers.

* Bibliography
Vasilakos, K. (2022). A Networked Hybrid Interface for Audience Sonification and Machine Learning. Revista Vórtex, 10(1) http://dx.doi.org/10.33871/23179937.2022.10.1.4695

Collins, N. (2015). Live Coding and Machine Listening. In Proceedings of the First International Conference on Live Coding (pp. 8). Leeds, UK.

The Cambridge companion to electronic music. Cambridge: Cambridge University Press.

Fiebrink, R., & Sonami, L. (2020). Reflections on Eight Years of Instrument Creation with Machine Learning. In R. Michon, & F. Schroeder, Proceedings of the International Conference on New Interfaces for Musical Expression (pp. 282–288). Birmingham, UK: Birmingham City University.

Baalman, M. (2020). The machine is learning.

#+REVEAL: split

Amershi, S., Cakmak, M., Knox, W. B., & Kulesza, T. (2014). Power to the People: The Role of Humans in Interactive Machine Learning. AI Magazine, 35(4), 105–120. http://dx.doi.org/10.1609/aimag.v35i4.2513

Crab, S. (2013). The ‘Telharmonium’ or ‘Dynamophone’ Thaddeus Cahill, USA 1897.

Cocker, E. (2018). What now, what next — kairotic coding and the unfolding future seized. Digital Creativity, 29(1), 82–95. http://dx.doi.org/10.1080/14626268.2017.1419978/

Fischman, R. (2011). Back to the parlour. Sonic Ideas – Ideas Sónicas, 3(2): 53–66.
